

#apiVersion: extensions/v1beta1
kind: Deployment
apiVersion: v1
metadata:
  name: "test-deployment"
  namespace: "jenkins"
spec:
  selector:
    matchLabels:
      app: "test"
  replicas: 2
  template:
    metadata:
      labels:
        app: "test"
    spec:
      containers:
      - image: 160357565307.dkr.ecr.us-west-2.amazonaws.com/railsapp:latest
        imagePullPolicy: Always
        name: "test"
        ports:
        - containerPort: 80
        

