apiVersion: v1
kind: Deployment
metadata:
  name: "test-deployment"
  namespace: "test"
spec:
  selector:
    matchLabels:
      app: "test"
  replicas: 2
  template:
    metadata:
      labels:
        app: "test"
    spec:
      containers:
      - image: 160357565307.dkr.ecr.us-west-2.amazonaws.com/railsapp:latest
        imagePullPolicy: Always
        name: "test"
        ports:
        - containerPort: 80
        
 ---
